version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tasks
    volumes:
      - db_data:/var/lib/mysql

  task-service:
    build:
      context: ./task-service
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: tasks

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - task-service

volumes:
  db_data:
